<a href="https://colab.research.google.com/github/salvadorGoros/miner-a-de-datos/blob/main/bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np
import pandas as pd

data={
    'correo': [
        "gana dinero rapido",
        "oferta exclusiva gratis",
        "reunion mañana",
        "adjunto el reporte",
        "ganapremio gratis"
    ],
    'clase': [
        "spam",
        "spam",
        "no spam",
        "no spam",
        "spam",
    ]
}

df= pd.DataFrame(data)
print(df)

                    correo    clase
0       gana dinero rapido     spam
1  oferta exclusiva gratis     spam
2           reunion mañana  no spam
3       adjunto el reporte  no spam
4        ganapremio gratis     spam


In [18]:
# Convertir el texto en una matriz de características
vectorizador = CountVectorizer()
x= vectorizador.fit_transform(df['correo'])
print(x.toarray())

[[0 1 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 0 0 0 0 0]]


In [19]:
# Variable objetivo
y = df['clase']
# Entrenar el modelo
modelo = MultinomialNB()
modelo.fit(x,y)
# Predecir la clase de un nuevo correo
nuevo_correo = ['reunion ayer']
correo_vectorizado = vectorizador.transform(nuevo_correo)
prediccion = modelo.predict(correo_vectorizado)
print(prediccion)

['no spam']


In [20]:
palabras = vectorizador.get_feature_names_out()
tabla_prob = pd.DataFrame(
    modelo.feature_log_prob_,
    columns=palabras,
    index=modelo.classes_
)
print(tabla_prob)

          adjunto    dinero        el  exclusiva      gana  ganapremio  \
no spam -2.140066 -2.833213 -2.140066  -2.833213 -2.833213   -2.833213   
spam    -2.995732 -2.302585 -2.995732  -2.302585 -2.302585   -2.302585   

           gratis    mañana    oferta    rapido   reporte   reunion  
no spam -2.833213 -2.140066 -2.833213 -2.833213 -2.140066 -2.140066  
spam    -1.897120 -2.995732 -2.302585 -2.302585 -2.995732 -2.995732  


In [21]:
palabras = vectorizador.get_feature_names_out()
tabla_prob = pd.DataFrame(modelo.feature_log_prob_, columns=palabras,index=modelo.classes_)

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np
import pandas as pd

data ={
    "reseña":[
          "el producto funciona excelente",
        "muy buena calidad",
        "el producto llegó dañado",
        "muy mala calidad",
        "excelente producto y calidad"
    ],
    "clasificacion":[
            "satisfecho",
        "satisfecho",
        "insatisfecho",
        "insatisfecho",
        "satisfecho"
    ]

}
df = pd.DataFrame(data)

In [23]:
#vectorizacion del texto
# Re-create df and y for sentiment analysis to ensure correct data is used
data_sentiment = {
    "reseña":[
          "el producto funciona excelente",
        "muy buena calidad",
        "el producto llegó dañado",
        "muy mala calidad",
        "excelente producto y calidad"
    ],
    "clasificacion":[
            "satisfecho",
        "satisfecho",
        "insatisfecho",
        "insatisfecho",
        "satisfecho"
    ]
}
df_sentiment = pd.DataFrame(data_sentiment)

vectorizer = CountVectorizer()
x = vectorizer.fit_transform(df_sentiment['reseña'])
print(x.toarray())

# Define the target variable 'y' from the sentiment analysis DataFrame
y = df_sentiment['clasificacion']

#entrenar modelo
modelo = MultinomialNB() #sepacion de datos
modelo.fit(x,y) # entrena por separado
# Comentario nuevo
nuevo = ["producto mala calidad"]
X_new = vectorizer.transform(nuevo)

# Predicción
prediccion = modelo.predict(X_new) # Corrected 'model' to 'modelo'
probabilidades = modelo.predict_proba(X_new) # Corrected 'model' to 'modelo'

print("Comentario:", nuevo[0])
print("Clasificación predicha:", prediccion[0])
print("Probabilidades:", probabilidades)

[[0 0 0 1 1 1 0 0 0 1]
 [1 1 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 1 1 0]
 [0 1 0 0 1 0 0 0 0 1]]
Comentario: producto mala calidad
Clasificación predicha: satisfecho
Probabilidades: [[0.49107811 0.50892189]]
