<a href="https://colab.research.google.com/github/salvadorGoros/miner-a-de-datos/blob/main/CHI-CUADRADO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
from scipy import stats
import numpy as np

# Tabla de frecuencias observadas
tabla = np.array([
    [40, 20],
    [30, 30]
])

In [6]:
# REaliza la prueba de chi-cuadrado de independencia stats.chi2_contingency
#devuelve el estadístico chi_cuadrado, el p-value,los grados de libertad y las frecuencias esperadas
chi2, p_value, gl, esperados = stats.chi2_contingency(tabla, correction=False)

In [7]:
# Imprime resultados
print(f"Chi-cuadrado = {chi2:.4f}")
print(f"p-value = {p_value:.4f}")
print(f"Grados de libertad = {gl}")
print("Frecuencias esperadas:")
print(esperados)

alpha = 0.05

if p_value < alpha:
  print("Hay evidencia suficiente para determinar que hacer ejercicio depende del genero")
else:
    print("No hay evidencia suficiente para determinar que hacer ejercicio depende del genero")

Chi-cuadrado = 3.4286
p-value = 0.0641
Grados de libertad = 1
Frecuencias esperadas:
[[35. 25.]
 [35. 25.]]
No hay evidencia suficiente para determinar que hacer ejercicio depende del genero


Ejercicio 1:
En una encuesta realizada en dos ciudades (Ciudad A y Ciudad B), se preguntó a los habitantes cuál era su medio de transporte preferido: automóvil o transporte público.

Los resultados fueron:
               Automóvil    Transporte Público
Ciudad A    85    65
Ciudad B    50    100

¿Existe una relación significativa entre la ciudad de residencia y la preferencia de transporte? Usa:
𝛼 = 0.05

In [13]:
tabla1 = np.array([
    [85, 65],
    [50, 100]
])
chi21, p_value1, gl1, esperados1 = stats.chi2_contingency(tabla1, correction=False)
print(f"Chi-cuadrado = {chi21:.4f}")
print(f"p-value = {p_value1:.4f}")
print(f"Grados de libertad = {gl1}")
print("Frecuencias esperadas:")
print(esperados1)

alpha = 0.05

if p_value1 < alpha:
  print("Existe una relación significativa entre la ciudad de residencia y la preferencia de transporte")
else:
    print("No existe una relación significativa entre la ciudad de residencia y la preferencia de transporte")

Chi-cuadrado = 16.4983
p-value = 0.0000
Grados de libertad = 1
Frecuencias esperadas:
[[67.5 82.5]
 [67.5 82.5]]
Existe una relación significativa entre la ciudad de residencia y la preferencia de transporte


**Ejercicio 2:
Un investigador de salud pública quiere saber si el nivel educativo influye en el consumo de tabaco. Encuesta a 200 personas y obtiene:
                       Fuma    No Fuma
Sin estudios    40    20
Bachillerato    35    45
Universidad    15    45
¿El nivel educativo está relacionado con el hábito de fumar? Usa
𝛼 = 0.05**

In [14]:
tabla2 = np.array([
    [40, 20],
    [35, 45],
    [15, 45]
])
chi22, p_value2, gl2, esperados2 = stats.chi2_contingency(tabla2, correction=False)
print(f"Chi-cuadrado = {chi22:.4f}")
print(f"p-value = {p_value2:.4f}")
print(f"Grados de libertad = {gl2}")
print("Frecuencias esperadas:")
print(esperados2)

alpha = 0.05

if p_value2 < alpha:
  print("El nivel educativo está relacionado con el hábito de fumar")
else:
    print("El nivel educativo no está relacionado con el hábito de fumar")

Chi-cuadrado = 21.1279
p-value = 0.0000
Grados de libertad = 2
Frecuencias esperadas:
[[27. 33.]
 [36. 44.]
 [27. 33.]]
El nivel educativo está relacionado con el hábito de fumar


Ejercicio 3:
Un nutriólogo quiere saber si el tipo de dieta que sigue una persona está relacionado con su nivel de colesterol. Evalúa a 180 pacientes y registra:

                         Colesterol Alto    Colesterol Normal
Dieta vegana    10    50
Dieta mixta    30    40
Dieta carnívora    45    5
¿Existe relación entre el tipo de dieta y el nivel de colesterol? Usa
𝛼 = 0.05

In [16]:
tabla3 = np.array([
    [10, 50],
    [30, 40],
    [45, 5]
])
chi23, p_value3, gl3, esperados3 = stats.chi2_contingency(tabla3, correction=False)
print(f"Chi-cuadrado = {chi23:.4f}")
print(f"p-value = {p_value3:.4f}")
print(f"Grados de libertad = {gl3}")
print("Frecuencias esperadas:")
print(esperados3)

alpha = 0.05

if p_value3 < alpha:
  print("Existe relación entre el tipo de dieta y el nivel de colesterol")
else:
    print("No existe relación entre el tipo de dieta y el nivel de colesterol")

Chi-cuadrado = 59.7240
p-value = 0.0000
Grados de libertad = 2
Frecuencias esperadas:
[[28.33333333 31.66666667]
 [33.05555556 36.94444444]
 [23.61111111 26.38888889]]
Existe relación entre el tipo de dieta y el nivel de colesterol
