<a href="https://colab.research.google.com/github/salvadorGoros/miner-a-de-datos/blob/main/ejercicios_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ejercicios numpy**

In [3]:
import pandas as pd
import numpy as np
from numpy import random

# tipos de array
array_0 = np.array(5)
print(array_0)

array_1 = np.array([1,2,3,4,5,6])
print (array_1)

array_2 = np.array([[1,2,3],[4,5,6]])
print (array_2)

array_3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print (array_3)

5
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [19]:
# index de los array
print(array_1[0])
print(array_2[0][1])
print(array_2[1][1])
print(array_3[0][2][0]) # dimensión, fila, columna

1
2
5
7


In [23]:
# shape
print(array_1.shape)
print(array_2.shape)
print(array_3.shape)

(6,)
(2, 3)
(1, 4, 3)


In [24]:
from numpy._core.fromnumeric import reshape
# reshape
print(array_1.reshape(1,6))
print(array_2.reshape(3,2))
print(array_3.reshape(2,3,2))

[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [28]:
# Concatenar
print(np.concatenate((array_1,array_1)))

[1 2 3 4 5 6 1 2 3 4 5 6]


In [31]:
# Slit
print(np.split(array_1,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
# where
print(np.where(array_1 == 3))

(array([2]),)


In [35]:
# ordenar los datos
array_n = np.array([10,50,2,0,7,6])
print(np.sort(array_n))

[ 0  2  6  7 10 50]


In [36]:
# ordenar descendente
print(np.sort(array_n)[::-1])

[50 10  7  6  2  0]


In [39]:
# random
numero = random.randint(100,200,1) #(inicio,fin,num de elementos)
print(numero)

[192]


In [40]:
numero2 = random.randint(10, size=(5))
print(numero2)

[5 0 9 3 3]


In [41]:
numero3 = random.randint(10, size=(2,3))
print(numero3)

[[4 7 0]
 [9 9 2]]


In [48]:
# Numeros aleatorios decimales
numero4 = random.rand()
print(round(numero4,2))

1.0


In [49]:
numero5 = random.rand() + 5
print(numero5)

5.947193545163883


In [50]:
numero6= random.rand(3,5)
numero6

array([[0.60760741, 0.04858832, 0.51093234, 0.1444595 , 0.7909115 ],
       [0.2517955 , 0.10821616, 0.33164254, 0.17936868, 0.45229984],
       [0.02442666, 0.51511976, 0.29174215, 0.40051074, 0.98183007]])

In [61]:
# Listas
listas_nombres = ["juan","pedro","maría"]
print(random.choice(listas_nombres))

maría


**Ejercicio**

**Crea un array de 10 números aleatorios enteros entre 0 y 100.
Crea un array de 5 números aleatorios decimales entre 0 y 1.
Crea dos arrays de números aleatorios enteros de longitud 5 y concaténalos.
Crea un array de 10 números aleatorios enteros y sepáralo en dos arrays de 5 elementos cada uno.
Crea una matriz de 3x3 con números aleatorios decimales entre 0 y 1.
Crea un array de 10 números aleatorios enteros y selecciona 3 elementos al azar.
Crea un array de 10 números aleatorios enteros entre 0 y 100 y calcula la media.**

In [88]:
#Crea un array de 10 números aleatorios enteros entre 0 y 100.
numero = random.randint(0,100,10)
print(numero)
#Crea un array de 5 números aleatorios decimales entre 0 y 1.
numero2 = np.random.rand(5)
print(numero2)
#Crea dos arrays de números aleatorios enteros de longitud 5 y concaténalos.
array_a = random.randint(20, size=(5))
array_b = random.randint(20, size=(5))
print(np.concatenate((array_a,array_b)))
#Crea un array de 10 números aleatorios enteros y sepáralo en dos arrays de 5 elementos cada uno.
array_c = random.randint(10, size=(10))
print(np.split(array_c,2))
#Crea una matriz de 3x3 con números aleatorios decimales entre 0 y 1
array_d = random.rand(3,3)
array_d
#Crea un array de 10 números aleatorios enteros y selecciona 3 elementos al azar.
array6 = random.randint(0,100,size=(10))
seleccion = random.choice(array6,3)

print("Array:", array6)
print("3 elementos al azar:", seleccion)
#Crea un array de 10 números aleatorios enteros entre 0 y 100 y calcula la media.
array7 = random.randint(0,100,size=(10))
media = np.mean(array7)

print("Array:", array7)
print("Media:", media)

[18 70 56 36 23 19 32 33 34 66]
[0.98461777 0.89712858 0.80603868 0.65457582 0.88511698]
[16  3 14  6  4  2  0  3  6 10]
[array([1, 7, 7, 9, 9]), array([7, 8, 2, 8, 3])]
Array: [91 57 44 69 67 28 77 55 68 56]
3 elementos al azar: [69 77 91]
Array: [77 59 23 96 79 80 60 58 55 82]
Media: 66.9
